import Categories from "./Categories";
import jacksonJS11_1Image from "./images/2910121503_1.png"
import jacksonJS11_2Image from "./images/2910121503_2.png"
import jacksonJS11_3Image from "./images/2910121503_3.png"
import jacksonJS11_4Image from "./images/2910121503_4.png"
import ibanezGRG170_1Image from "./images/GRG170DX-BKN_1.png"
import ibanezGRG170_2Image from "./images/GRG170DX-BKN_2.png"
import ibanezGRG170_3Image from "./images/GRG170DX-BKN_3.png"
import ibanezGRG170_4Image from "./images/GRG170DX-BKN_4.png"
import harleyBentonCLDImage from "./images/HarleyBentonCustomLineCLD-41SEWN.png"
import harleyBentonCLD_1Image from "./images/HarleyBentonCustomLineCLD-41SEWN_1.png"
import TakamineEF341SCImage from "./images/Takamine EF341SC.png"
import TakamineEF341SC_1Image from "./images/Takamine EF341SC_1.png"
import TakamineEF341SC_2Image from "./images/Takamine EF341SC_2.png"
import TakamineEF341SC_3Image from "./images/Takamine EF341SC_3.png"
import FenderCDSBV3Image from "./images/Fender CD-60 SB V3.png"
import FenderCDSBV3_1Image from "./images/Fender CD-60 SB V3_1.png"
import FenderCDSBV3_2Image from "./images/Fender CD-60 SB V3_2.png"
import KawaiK300WHPSLPianoImage from "./images/Kawai K-300 WHP SL Piano.png"
import YamahaP121MPEPianoImage from "./images/Yamaha P 121 M PE Piano.png"
import Seiler116KonsoleChromImage from "./images/Seiler 116 Konsole Chrom.png"

class Product{
    constructor(id, name, mainCategoryNo, subCategoryNo, price, description, images, popular){
        this.id = id;
        this.name = name;
        this.mainCategory = Categories[mainCategoryNo].name;
        this.subCategory = Categories[mainCategoryNo].subCategories[subCategoryNo].name;
        this.price = price;
        this.description = description;
        this.images = images;
        this.popular = popular
    }
}

const Products = [
    new Product(0, "Jackson JS11 Dinky 2-Point", 0, 0, 1200, ["Bolt-on neck","Body: Basswood","Maple neck with modern C-shape","Maple fretboard","Fretboard radius: 350 mm","Dot-inlays","22 Frets","Scale: 648 mm","Nut width: 42 mm","Dual action truss rod","2x TE-style single coil pickups","Electronics: 1 Volume knob, 1 Tone knob, 3-way switch","Chrome hardware","Die-cast machine heads","09-042 Strings","Finish: Blue metallic high gloss"], [jacksonJS11_1Image, jacksonJS11_2Image, jacksonJS11_3Image, jacksonJS11_4Image], true ),
    new Product(12, "Jackson JS11 Dinky 2-Point", 0, 0, 1200, ["Bolt-on neck","Body: Basswood","Maple neck with modern C-shape","Maple fretboard","Fretboard radius: 350 mm","Dot-inlays","22 Frets","Scale: 648 mm","Nut width: 42 mm","Dual action truss rod","2x TE-style single coil pickups","Electronics: 1 Volume knob, 1 Tone knob, 3-way switch","Chrome hardware","Die-cast machine heads","09-042 Strings","Finish: Blue metallic high gloss"], [jacksonJS11_1Image, jacksonJS11_2Image, jacksonJS11_3Image, jacksonJS11_4Image], true ),
    new Product(1, "Ibanez GRG170DX-BKN",0,0, 5380,["Bolt-on neck","Body: Lime Tree","Maple handle with modern C-shape","Rosewood fretboard","Fretboard radius: 320 mm","Dot-inlays","25 Frets","Scale: 650 mm", "Nut width: 45 mm","Dual action truss rod","2x TE-style single coil pickups","Electronics: 1 Volume knob, 1 Tone knob, 5-way switch","Chrome hardware","Die-cast machine heads","09-042 Strings","Finish: Black metallic high gloss"],[ibanezGRG170_1Image, ibanezGRG170_2Image, ibanezGRG170_3Image, ibanezGRG170_4Image]),
    new Product(2, "Harley Benton Custom Line CLD-41SE WN",0,1, 289, ["Dreadnought design","Dovetail construction","Solid sitka spruce top","Scalloped X-bracing","Walnut body","Mahogany neck","Pau Ferro fretboard","Abalone Hexagon fretboard inlays","Abalone body binding","White fretboard and headstock binding","Modified Oval C neck profile","Scale: 643 mm","Nut width: 43 mm","Bone nut","20 Frets","Compensated saddle","Pau Ferro bridge","Gold-plated diecast DLX machine heads","Pickup system: Fishman Presys-II preamp system with built-in tuner","Strings: D'Addario XTAPB1253 Light (Article Nr 471307), .012 - .053","Colour: Natural matte"],[harleyBentonCLDImage,harleyBentonCLD_1Image ]),
    new Product(3,"Takamine EF341SC", 0,1,839,["Bruce Springsteen model","Body shape: Dreadnought with cutaway","Body and sides: Maple","Top: Solid cedar","Bridge and fingerboard: Rosewood (Dalbergia Latifolia)","Fretboard inlays: Mother of pearl snowflake dots","CT4B preamp with pickup and tuner","Ex-factory stringing: Daddario EXP16 .012 - .053 (Article Nr 147540)","Colour: High gloss black","Case included"],[TakamineEF341SCImage, TakamineEF341SC_1Image, TakamineEF341SC_2Image, TakamineEF341SC_3Image]),
    new Product(4,"Fender CD-60 SB V3",0,1,105,["Design: Dreadnought","Top: Laminated spruce","Bottom and sides: Laminated mahogany","Neck: Mahogany","Fretboard and bridge: Walnut","20 Frets","Scale: 643 mm","Nut width: 43 mm (1.69)","Colour: Sunburst","Strings: Fender 880L (Art.254209)"],[FenderCDSBV3Image, FenderCDSBV3_1Image, FenderCDSBV3_2Image]),
    new Product(5,"Kawai K-300 WH/P SL Piano",2,1,5699,["Millennium III hammer mechanics with ABS carbon parts of unmatched sturdiness and robustness","Mahogany hammer core","Hammer heads with bottom felt","Extended keyboard","100 cm Sheet music rest","Slowly closing keyboard cover","88 Keys","3 Pedals","Dimensions (H x W x D): 122 x 149 x 61 cm","Weight: 227 kg","Finish: White, polished with chrome fittings","Delivery Germany-wide and first tuning service included"],[KawaiK300WHPSLPianoImage]),
    new Product(6,"Yamaha P 121 M PE Piano",2,1,6444,["Designed in Europe to European preferences, the P121 boasts exquisite cabinetry, European spruce soundboard and back posts and the rich, expressive voice of a full-sized upright.","Dimensions: Width: 152 cm, Depth: 60 cm, Height: 121 cm","Weight: 215 kg","Colour: Black, polished","Piano bench, piano light and Germany-wide delivery included"],[YamahaP121MPEPianoImage], true),
    new Product(7,"Seiler 116 Konsole Chrom",2,1,10890,["From German production","Renner-action","Abel-hammer heads","3 Pedals","Height: 117 cm","Width: 146 cm","Depth: 56 cm","Knee height: 67 cm","Weight: 215 kg","Colour: Black Polished","Transport nationwide included in the price - will be intonated and tuned by our master piano builder before delivery","5 Years warranty"],[Seiler116KonsoleChromImage]),
    new Product(14000,"Harley Benton SC-450Plus HB Vintage Series",0,0,2560,["Electric Guitar","Vintage Series","Body: Mahogany","Arched top: AAA flamed maple","Set-in neck: Mahogany","Fretboard: Pau Ferro","Fretboard inlays: Trapezoid","Neck profile: C","Radius: 350 mm","Cream-coloured bindings on the body and neck","22 Medium jumbo frets","Scale: 628 mm","Nut width: 43 mm","Double action truss rod","Pickup: 2 Roswell LAF Alnico-5 vintage-style humbuckers","3-Way pickup selector switch","2 Volume controls with push/pull function for coil split","2 Tone controls","Chrome-plated DLX hardware","DLX Tune-o-matic bridge","DLX Kluson-style machine heads","Ex-factory stringing: D'Addario EXL .010 - .046","Colour: Honey burst gloss"],[]),
    new Product(15146,"Harley Benton SC-Custom II SPAF",0,0,2670,["Electric Guitar","Custom Line Series","Mahogany body","AAAA Flamed maple veneer top","Mahogany neck","Roasted jatoba fretboard","White pearloid crowns fretboard inlays","Modern-C neck profile - Thickness at the 1st fret: 20 mm; Thickness at the 12th fret: 22 mm","Cream binding","Fretboard radius: 350 mm (13.78)","Scale: 628 mm","Nut width: 42 mm (1.65)","Graphite nut","22 Medium jumbo frets","2 Roswell HAF Zebra AlNiCo-5 humbucker pickups","2 Volume controls","1 Tone control with push/pull function for coil split","3-Way switch","WSC Tune-O-Matic bridge","Chrome hardware","Grover machine heads","Colour: Paradise Satin Flame"],[]),
    new Product(16591,"Harley Benton SC-DLX Gotoh Pelham Blue",0,0,2430,["Electric guitar","Deluxe Series","Carved-top Nyatoh body with weight relief","Set mahogany neck with modern C profile","Rosewood (Dalbergia latifolia) fingerboard","Trapezoid inlays","7-ply binding","Fingerboard radius: 305 mm","Scale: 628 mm (24.75”)","Nut width: 43 mm","Graph Tech TUSQ nut","22 Blacksmith medium jumbo stainless steel frets","Pickups: 2 x Tesla VR-2 alnico 5 humbucker","Controls: Bridge volume, neck volume, master tone w/push-pull for coil split","Switch: 3-way toggle","Double-action truss rod","Gotoh tune-o-matic bridge","Gotoh Kluson-style machine heads","Hardware finish: Gold","Stock strings: .010 - .046","Finish: High-gloss Pelham Blue"],[]),
    new Product(18771,"Harley Benton SC-DLX Gotoh Shell Pink",0,0,2650,["Electric guitar","Deluxe Series","Carved-top Nyatoh body with weight relief","Set mahogany neck with modern C profile","Rosewood (Dalbergia latifolia) fingerboard","Trapezoid inlays","7-ply binding","Fingerboard radius: 305 mm","Scale: 628 mm (24.75”)","Nut width: 43 mm","Graph Tech TUSQ nut","22 Blacksmith medium jumbo stainless steel frets","Pickups: 2 x Tesla VR-2 alnico 5 humbucker","Controls: Bridge volume, neck volume, master tone w/push-pull for coil split","Switch: 3-way toggle","Double-action truss rod","Gotoh tune-o-matic bridge","Gotoh Kluson-style machine heads","Hardware finish: Gold","Stock strings: .010 - .046","Finish: Shell Pink Satin"],[]),
    new Product(1891,"Epiphone Les Paul Studio Ebony",0,0,760,["Electric Guitar","Body: Mahogany","Top: Maple veneer","Neck: Mahogany","Fretboard: Pao Ferro","Trapezoid fretboard inlays","Neck profile: 60 Slim Taper D","Scale: 629 mm (24.75)","Nut width: 43 mm (1.693)","22 Frets","Pickups: 2 Epiphone Alnico Classic (neck and bridge) humbuckers","Controls: 2 volume and 2 tone CTS electronics","Locktone ABR Tune-o-matic bridge","Stopable tailpiece","Grover 18: 1 machine heads","Colour: Ebony"],[]),
    new Product(1961,"Gibson Les Paul Studio Ebony",0,0,420,["Electric Guitar","Body: Mahogany","Ultra Modern Weight Relief - weight-reduced body","Top: Maple","Neck: Mahogany","Neck profile: Slim Taper","Fretboard: Rosewood (Dalbergia latifolia)","Acrylic trapezoid fretboard inlays","Graphtech nut","Nut width: 43 mm","Scale: 628 mm","22 Cryogenically treated medium frets","Pickups: 490R and 498T humbuckers","2 x Volume controls (push / pull for coil tap)","2 x Tone controls","Aluminium Tuneomatic bridge","Aluminium stop bar","Colour: Tangerine burst","Includes soft shell case","Made in USA"],[]),
    new Product(23749058407,"Thomann GCL-420 MKII Bb-Clarinet",1,0,620,["Bb Clarinet","New, improved version","German fingering","20 Keys","6 Tone holes","Made entirely of natural grenadilla wood (Dalbergia melanoxylon)","Adjustable thumb rest with ring for the strap","Silver-plated key system","2 Barrels: 58 mm and 60 mm","Each instrument is checked in our master workshop for woodwind instruments and readjusted prior to sale","Includes ESM mouthpiece, Rovner ligature, BG thumb rest, Thomann de Luxe wiper, microfibre polishing cloth, tooth rest, grease and luxury lightweight case with shoulder strap"],[]),
    new Product(26500,"Thomann GCL-422 MKII Bb-Clarinet",1,0,540,["Bb Clarinet","New, improved version","German key system","22 Keys","6 Rings","Completely made of natural grenadilla wood (Dalbergia melanoxylon)","Adjustable thumb rest with ring for strap","Silver-plated key system","Two barrels: 58 and 60 mm","Includes: ESM mouthpiece, Rovner ligature, BG thumb rest, Thomann de luxe cloth, microfibre polishing cloth, tooth rest, grease and luxury light case with carrying strap","Each instrument is checked in our master workshop for woodwind instruments and set up prior to selling."],[]),
    new Product(17100,"Schreiber D-26 Bb-Clarinet - NEW",1,0,560,["Bb Clarinet","Made of grenadilla wood (Dalbergia melanoxylon)","German fingering","20 Keys","6 Rings","Adjustable thumb ring","2 Barrels","Includes case and mouthpiece","5 Year manufacturer warranty on body and mechanics","Made in Germany"],[]),
    new Product(46145,"Thomann GCL-416 Synthetic Line",1,0,720,["Junior Bb Clarinet","Synthetic Line","German fingering","Key system suitable for children","16 Keys","6 Tone holes","Made of synthetic material","Adjustable thumb rest with ring for the strap","Silver-plated key system","2 Barrels","Includes ESM mouthpiece, GF ligature, BG thumb rest, Kölbl wiper, tooth rest, grease and luxury lightweight case with shoulder strap","Each instrument is checked in our master workshop for woodwind instruments and readjusted before sale"],[]),
    new Product(45473,"Yamaha YCL-457II-20 Clarinet",1,0,1480,["Bb Clarinet","German key system","20 Keys","6 Rings","Normal barrel","Made of grenadilla wood","Elevated flat plateau for the thumb hole, F-lift left","Eb / Bb side key with metal base","A and G-sharp keys coupled","Synthetic cork","Adjustable thumb rest with ring for carrying strap","Lightweight case with backpack set, textile ligature from BG and M3D mouthpiece included"],[]),
    new Product(96961,"Yamaha YCL-457II-22 Clarinet",1,0,1635,["Bb Clarinet","German fingering","Blackwood body (Dalbergia melanoxylon)","22 keys","6 rings","Normal barrels","Increased flat plateau for thumb hole","F lever and Eb lever on the left","Double F/C key","Eb/Bb palm keys with metal foot","Twelfth connection","Coupling of A and G sharp keys","Synthetic cork","Adjustable thumb rest with a ring for carrying cord","Incl. light case with backpack straps, textile ligature from BG and M3D mouthpiece"],[]),
    new Product(6264,"Oscar Adler & Co. 322 Bb-Clarinet",1,0,654,["Bb Clarinet","German system","22 Keys","6 Rings","4 Trill keys on the upper joint","Forked Bb and F mechanism","Auxiliary Eb and F key","B/C# Trill key","Double C key","Twelfth key","From selected blackwood (Dalbergia melanoxylon)","Silver-plated mechanism","Adjustable thumb rest","Comes with two barrels (56 / 57.5 mm)","Incl. ESM W3E mouthpiece, BG ligature, accessories, and a gig bag with carrying sling system and sheet music pocket"],[]),
    new Product(65339,"F.A. Uebel 621 Bb-Clarinet",1,0,590,["Bb Clarinet","African Blackwood (Dalbergia melanoxylon), dried naturally","German fingering","Fork F/B mechanism","B-C# Trill","F Lever","21 Keys","6 Rings","Silver plated nickel silver, Monel tubes","Silver plated nickel silver pillars","2 Barrels","Including ESM mouthpiece, Rovner ligature and case"],[]),
    new Product(49006,"Thomann Antique Tenor Sax",1,1,1620,["Tenor Saxophone","Special series","High F# key","Tilter","Adjustable thumb rest","Brass body and keys","Quick response","Very bright and rich in overtones","Antique finish","Includes mouthpiece and case"],[]),
    new Product(20333,"Thomann TTS-350 Tenor Sax",1,1,1405,["Tenor Saxophone","High F# key","Rocker arm","Adjustable thumb rest","Body and keys made of brass","Lacquered completely with gold lacquer","Response and sound character balanced and uniform over the entire range","Mouthpiece and case included"],[]),
    new Product(75442,"Thomann TTS-180 Black Tenor Saxophone",1,1,780,["Tenor Saxophone","High F# key","Front F key","Body, neck, and mechanical parts made from brass","Separate adjustment screws for D, E, F, A & B","Adjustable thumb hooks made from metal","G# and F# keys made from solid material","Easy to service, removable bell","Black body","Keys lacquered with gold varnish","Black Pisoni pads","Dark key buttons","Includes a light case and backpack straps"],[]),
    new Product(95771,"Startone STS-75 Tenor Sax",1,1,695,["Tenor Saxophone","Handmade","Copper body (92% copper)","High F# key","Artistic engraving","Brass keys","Body and keys in matte finish","Original Abalone inlays","Includes mouthpiece and lightweight case with backpack straps"],[]),
    new Product(73881,"Thomann MK IV Handmade Tenor Sax",1,1,1520,"Tenor Saxophone","New model","Successor of the YTS-475","New neck mount","Improved H/ C# connection","Separate key guards","High F# key","New octave key system as in the 62 series","Rocker arm","Drop-shaped fork F key","Silicon treated pads","Hand-engraved","Gold lacquer finish","Light case with rucksack straps and 4C mouthpiece included",[],[]),
    new Product(26990,"Yamaha YAS-280 Alto Sax",1,1,1460,["Alto Saxophone","School model","New model with improved S-bow receiver and improved low B-C# connection","Continuous key guards","Adjustable thumb rest","High F# key","Bell inner ring","Front F-key","Brass body","Key mechanism and body in gold lacquer","Included: Light case with backpack straps, Yamaha 4C Mouthpiece, saxophone strap and cork grease","Successor to the YAS-275"],[]),
    new Product(6475,"Thomann TAS-180 Black Alto Saxophone",1,1,865,["Alto Saxophone","High F# key","Front F-key","Body, S-bow, and screws made from brass","Separate adjustment screws for D, E, F, A & H","Adjustable thumb rest made of plastic","G# and F# key handles made of solid material","Bell is detachable and easy to service","Very comfortable and ergonomic mechanism for the left and right little finger","Black body","Gold lacquered keys","Black leather pad with metal resonators","Black finger inlays","Black padding","Dark finger inlays","Incl. light case with backpack straps","30 30-Day Money-Back Guarantee"],[]),
    new Product(34667,"Yanagisawa A-WO1 Alto Sax",1,1,942,["Alto Saxophone","New model","Revised key mechanism","New engraving design","Made from a new brass alloy","High F# key","Bb/C# tilter","Adjustable thumb rest","Included: Mouthpiece and new case with external accessory pocket and backpack straps"],[]),
    new Product(30002,"Kawai GL 10 WH/P Grand Piano",2,0,15600,["Grand Piano","Millennium III Mechanics","ABS Styran Mechanical Components","Sostenuto-pedal","Hammer heads with bottom felt","Slow closing key flap","Length: 153 cm","Colour: White polished","Weight: 282 kg","With piano bench","Including delivery nationwide via a piano delivery service and a communication service on site"],[]),
    new Product(51002,"Yamaha GB1 K Walnut Polished",2,0,13200,["88 Keys","3 Pedals (centre pedal: single tone holding pedal)","Length: 151 cm (5 ')","Width: 146 cm (57 )","Height: 99 cm (39 )","Weight: 261 kg (574 lbs)","Walnut polished","With piano bench","Including delivery nationwide via piano delivery and a talk service all over Germany"],[]),
    new Product(74001,"Seiler 186 Maestro Showroom model",2,0,30200,["Year of manufacture: 1933","Exemplary of the Steinway instruments inherent sound culture in its purest form","Perfection in detail, the rich scale of its tonal nuances and its soulful tone have made the model A-195 (A3) the instrument of choice for artists, institutions and private musicians alike","Length: 195 cm","5 Years Thomann warranty","This grand piano will be set up at your home with a high quality piano bench from Andexinger and tuned and re-toned according to your wishes"],[]),
    new Product(90043,"Steinway & Sons B-211",2,0,16420,["Year of manufacture: 1964","Exemplary for the Steinway instruments inherent sound culture in its purest form","The rich range of its tonal nuances and its soulful tone have made the model B-211 the instrument of choice for artists, institutions and private musicians","Length: 211 cm","Width: 148 cm","5 Years Thomann warranty","Weight: Approx. 345 kg","This grand piano will be set up at your home with a high-quality piano bench from Andexinger and tuned and re-toned according to your wishes"],[]),
    new Product(36620,"Steinway & Sons O-180",2,0,13460,["Manufacturing year: 1919","The O-180 grand piano provides an extremely precise and unique playing feeling","It meets the highest demands and offers all technical requirements with maximum inspiration - for the advanced player as well as for the professional musician","An exemplary for the sound culture inherent in Steinway instruments, in its purest form","Length: 180 cm","Width: 146.5 cm","Weight: approx. 280 kg","Surface: black high gloss polished","This grand piano will be set up at your home with a high-quality piano bench from Andexinger and tuned and re-toned according to your wishes"],[]),
    new Product(61992,"Kawai GL 50 E/P Grand Piano",2,0,12950,["Grand Piano","With duplex scale","Millennium III Mechanics","ABS Styran Mechanical Components","Sostenuto","Hammer heads with bottom felt","Slowly closing key flap","Length: 188 cm","Weight: 334 kg","Finish: Black polished","Incl. Piano bank and delivery nationwide via piano delivery service and a communication service on site"],[]),
    new Product(34776,"Steinway & Sons O-180 Makassar",2,0,12400,["Manufacturing year: 1906","Model: Steinway & Sons O-180","The grand piano O-180 provides an extremely precise and unique playing feeling","It meets the highest demands and offers all technical requirements with maximum inspiration - for the advanced player as well as for the professional musician","An exemplary for the sound culture inherent in Steinway instruments, in its purest form","Length: 180 cm","Width: 146.5 cm","Weight: approx. 280 kg","Surface: Makassar high gloss polished","This grand piano will be set up with a high-quality piano bench in Makassar optic and tuned and re-toned according to your wishes"],[]),
    new Product(12229,"Yamaha C 3 X PE Grand Piano",2,0,36405,["Striving to create a grand piano that is in harmony with the pianist, the developers of the CX series have created instruments that truly sing","Black polished","Length: 186 cm (6 '1 )","Width: 149 cm (59 )","Height: 101 cm (40 )","Weight: 320 kg (704 lbs)","With piano bench","Including delivery nationwide via piano delivery service and a customer talk service all over Germany"],[]),
    new Product(31114,"Yamaha b1 SC2 PWH",2,1,4750,["Silent Piano","88 Keys","Equipped with the Yamaha SC2 Silent System","Over 10 different sounds and USB port","This model offers the joy of playing a full-fledged Yamaha piano","3 Pedals","Dimensions (H x W x D): 109 x 149 x 54 cm","Weight: 193 kg","Finish: White polish","Includes piano bench, headphones, piano light and delivery nationwide by Klavierspedition","5 Year manufacturer's warranty"],[]),
    new Product(59994,"Yamaha b3 SNC",2,1,7640,["Upright Piano","Elegant cabinetry in traditional design","Larger dimensions and a more intricate construction result in a sound audibly richer in volume","Caster wheels for improved mobility","For the more advanced pianists, the b3 piano is the perfect combination of good playing and sound qualities","Solid soundboard made of spruce","Dimensions (W x H x D): 152 x 121 x 61 cm","Weight: 237 kg","Colour: Cherry matte","Piano bench, light and Germany-wide delivery included","5 Year factory warranty"],[]),
    new Product(24446,"Yamaha b1 OPDW Upright Piano",2,1,4690,["Walnut-like dark open-pored","88 Keys","3 Pedals","Dimensions (H x W x D): 109 cm (42 7/8) x 148 cm (58 1/4) x 54 cm (21 1/4)","Weight: 174 kg (383 lbs)","Piano bench and light included","Shipping within Germany (other countries on request) by piano movers included in the price"],[]),
    new Product(45659,"Yamaha b1 PEC",2,1,6450,["Upright Piano","88 Keys","3 Pedals","Colour: Black, polished","With chrome fittings","Piano bench and light included","Height: 109 cm (42 7/8)","Width: 148 cm (58 1/4)","Depth: 54 cm (21 1/4)","Weight: 174 kg (383 lbs)","5 Year factory warranty","Shipping within Germany (other countries on request) by piano transport is included in the price."],[]),
    new Product(34597,"Seiler 132 Konzert B Anniversary",2,1,4630,["Piano","Millennium III mechanics with incredibly sturdy and rigid ABS carbon parts","Mahogany hammer mouldings","Underfelted hammer heads","100 cm Sheet music rest","Extended keyboard","Slowly closing keyboard cover","88 Keys","3 Pedals","Dimensions (H x W x D): 122 x 149 x 61 cm","Weight: 227 kg","Surface: Polished black with chrome fittings","Delivery Germany-wide and first tuning service included"],[]),
    new Product(47583,"Sauter Piano, Used",2,1,4670,["Manufacturing year: 1958","Classical design with console","Height: 108 cm","Surface: Black Matt","Incl. a piano light and nationwide delivery at ground level by a piano forwarding agent"],[]),
    new Product(64579,"Kawai K-200 E/P Piano",2,1,6410,["Piano","Millennium III Upright Action with ABS carbon composites of unmatched stability and strength","Mahogany hammer core","Hammer heads with underfelt","100 cm music stand","Keyboard lid closes slowly","88 Keys","3 Pedals","Dimensions in cm (H x W x D): 114 x 149 x 57","Weight: 208 kg","Surface: Polished black","Includes delivery nationwide (Germany) via a piano shipping company and first on-site tuning service"],[]),
    new Product(16365,"Thomann DP-26",2,2,6490,["Digital Piano","88 Weighted keys with hammer action keyboard","20 Sounds","2 Demo songs","50 Styles","128 Voice polyphony","LED display","Layer mode","Split mode","Duo mode","Master EQ","Reverb","Chorus","Sequencer: 5 user songs - melody and accompaniment","Duet","Harmony","Music library: 60 preset songs","L-/ R- Hand exercises","Pitch bend","Metronome","Transpose-Function","Speaker: 2x 10 W","Connections: 2x headphones, MIDI out, USB MIDI, sustain, aux in/ out","Dimensions (W x D x H): 1365 x 366 x 137 mm","Weight: 12.9 kg","Colour: black","Includes power adapter, music stand and sustain pedal","Suitable bags: Art.394939 or Art.146377 (both not included)","Suitable protective cover: Art.497390 (not included)"],[]),
    new Product(94514,"Thomann DP-32 WH",2,2,7600,["Digital Piano","88 Weighted keys with hammer action","16 Sounds","60 Internal songs","128-Voice polyphony","Reverb","Sequencer with 5 user songs","Effects","Duet","Touch response","Voice demo","Metronome","Transpose function","3 Pedals","2 Headphone outputs","USB MIDI connection","2 AUX outputs","Amplifiers: 2x 20 W","Speakers: 2x 10 W","Dimensions: 1363 x 440 x 850 mm","Weight: 38.5 kg","Colour: White matte"],[]),
    new Product(15641,"Thomann DP-95 B",2,2,4920,["Digital Piano with Automatic Accompaniment","88 Weighted keys with hammer action keyboard","500 Sounds","200 Styles","60 Internal songs","2 Demo songs","LCD","128 Voice polyphony","Harmony","Reverb","Sequencer (3 user songs)","Sync Start, Sync Stop, Intro/Ending, Fill-In A, and Fill-In B functions","One touch setting","Chord and Dual/Split mode","Metronome","Transpose function","3 Pedals","Key cover","Speakers: 2x 25 W, 2x 20 W","Dimensions (W x D x H): 1380 x 514 x 906 mm","Weight: 53 kg","Colour: Black"],[]),
    new Product(34895,"Hemingway DP-501 MKII WH",2,2,9420,["Digital Piano","88 Weighted keys with hammer action keyboard","LCD display with blue backlit","16 Sounds","Reverb","Chorus","16 Demo songs","Polyphony: 64-tones","Metronome","Transpose-, split- and layer-function","3 Pedals","Slide in key cover","Internal recorder: 3 tracks, 90000 notes","USB MIDI recorder","Learn function","Duet mode","2 Headphone outputs","Line out L and R","Line in","MIDI Out","USB to host","USB to device","Bluetooth","Speaker system: 2x 20 Watts","Dimensions (W x D x H): 1400 x 490 x 860 mm","Weight: 54 kg","Colour: White","Includes power adapter"],[]),
    new Product(36174,"Hemingway DP-501 MKII RW",2,2,6490,["Digital Piano","88 Weighted keys with hammer action","LCD display with blue backlight","16 Sounds","64-Voice polyphony","16 Demo songs","Reverb","Chorus","Metronome","Transpose, split and layer function","3 Pedals","Retractable keyboard cover","Internal recorder: 3 tracks / 90000 notes","USB MIDI Recorder","Duet mode","Loudspeaker system: 2x 20 W","Dimensions (W x D x H): 1400 x 490 x 860 mm","Weight: 54 kg","Design: Rosewood","Power supply included"],[]),
    new Product(655236,"Kawai KDP-120 B",2,2,3465,"Digital Piano","Responsive Hammer Compact II (RHCII) keyboard with 88 weighted keys and three sensors","Harmonic imaging (HI)","Shigeru Kawai SK-EX concert grand piano sound with new Low Balance Volume feature for intelligent sound adjustment at low volume","Virtual Technician Smart Mode","15 sounds","192-note polyphony","Lesson function","Dual function","Four-hand mode","Metronome","Transposer","15 demo songs","Internal recorder (three songs, 10,000 notes)","Key cover","Three pedals","Bluetooth MIDI","USB MIDI","USB to host","Two headphone inputs","2 x 20 W speaker system","Dimensions (W x D x H): 1360 x 405 x 855 mm","Weight: 37 kg","Colour: Premium Black Satin","PS-154 power supply included",[],[]),
    new Product(76363,"Kawai KDP-120 W",2,2,9460,["Digital Piano","Responsive Hammer Compact II (RHCII) action with 88 weighted keys and a 3-fold sensor","Harmonic Imaging (HI)","88 Keys sampling","Shigeru Kawai SK-EX concert grand piano sound with new Low Balance Volume feature that intelligently adjusts the sound at the low volumes","Virtual Technician Smart Mode","15 Sounds","192 Polyphony voices","Lesson function","Dual Function","4 Hand Mode","Metronome","Transposer","15 Demo songs","Internal recorder (3 songs, 10,000 notes)","Retractable keyboard cover","3 Pedals","Bluetooth MIDI","USB Midi","USB to host","2 Headphone jacks","2 x 20 Watt speaker system","Dimensions (W x D x H): 1360 x 405 x 855 mm","Weight: 37 kg","Colour: Premium White Satin","Incl. a power supply PS-154"],[]),
    new Product(1555,"Thomann Gothic Black Cello 4/4",3,1,750,["Cello","Size: 4/4","Top, back and sides are made from laminated basswood","Neck is made from maple","Hardwood fingerboard","Wooden tuning pegs","Tailpiece with fine tuners","Height adjustable endpin","Strings: Jargar Classic Medium","Colour: Black","Incl. padded bag, composite bow, rosin","Set up in Germany at Thomann's string workshop"],[]),
    new Product(707406,"Lothar Semmlinger No. 135A Antiqued Cello 4/4",3,1,690,["Cello","4/4","Master instrument","Stradivari style","Finest solid spruce top","Very good elaboration","Beautifully flamed maple back, sides and neck","Finest ebony fittings","Stringing: A- and D-string Larsen chrome steel medium, G- and C-string Thomastik Spirocore tungsten medium","Antique lacquering","Golden brown lacquer on spirit base","Made in Germany"],[]),
    new Product(7326,"Harley Benton HBCE 990RD Electric Cello",3,1,640,["Electric Cello","Includes an active shadow pickup system","Neck: Maple","Fingerboard and tuning pegs: Birch","Aluminium tailpiece with fine tuners","Electronics: volume control, treble control, bass control","6.3 mm jack output with selector switch for connecting headphones or an amplifier","3.5 mm aux-in jack input for playback or playalong via mp3, smartphone, CD player, etc.","Colour: Red","Includes a bag, bow, rosin and supports for the abdominal area and knees"],[]),
    new Product(831,"Stentor SR1108 Cello Student II 4/4",3,1,4990,["Beginner's Cello Outfit","Model: Student II","Size: 4/4","Solid spruce top","Solid maple body","Fingerboard and pegs made from ebony (Diospyros crassiflora)","Scale length: Approx. 685 mm","Includes bag and bow"],[]),
    new Product(84476,"Gewa Germania 11L Paris Ant. Cello",3,1,645,["Cello","Lefthand / left-handed model","Size: 4/4","Old-imitated concert cello","Selected spruce top worked on clay","Sides and back made of selected European sycamore maple","Ebony furniture","Open-pored hand varnish on spirit base","Very good response due to thin varnish application","Made in Germany"],[]),
    new Product(91140,"Lothar Semmlinger No. 132A Antiqued Cello 4/4",3,1,460,["Cello","Size: 4/4","Stradivarius style","Top: Solid spruce","Maple back, sides and neck lightly flamed","Ebony fittings","Stringing: A- and D-string Larsen chrome steel medium, G- and C-string Thomastik Spirocore tungsten medium","Antique lacquer finish","Red brown lacquer on alcohol base","Made in Germany"],[]),
    new Product(903,"NS Design NXT4a-CO-BK Cello",3,1,560,["4-String Electric Cello","Dual mode active output","With Polar Pickup System","Body: Maple","Maple neck","Richlite composite fingerboard with dot markers","Neck reinforced with steel rod","Volume and tone controls","Scale: 69.5 cm","Tuning: C - G - D - A","Weight: 1.9 kg","Colour: Satin black","Tripod stand, charger and gig bag included"],[]),
    new Product(12747,"Stentor SR1102 Cello Student I 1/4",3,1,630,["Cello Beginner's Set","Student model","Size: 1/4","Solid spruce top","Solid maple body","Tuning pegs made of hardwood","Fingerboard made of malas (Homalium foetidium)","Bag and bow included"],[]),
    new Product(601,"Roth & Junius Europe 4/4 AS Student Cello",3,1,950,["Cello set","4/4 size","With Jargar Classic strings","Solid spruce top","Solid maple back","Maple neck and sides","Fingerboard: Ebony","Tailpiece with fine tuners","Colour: Slightly antique. painted matte","Made in Europe","Includes bow","Ready to play in Germany in the Thomann Streicher workshop"],[]),
    new Product(105256,"Harley Benton UK-10S Ukulele",3,2,40,["Ukulele","Concert size","Solid spruce top","Bottom and sides: Mahogany (Khaya senegalensis)","Neck: Okume","Fretboard: Blackwood (Pinus radiata)","Dot fretboard inlays","18 Frets","Scale: 377 mm","Nut width: 35 mm","Bridge: Blackwood","Chrome diecast machine heads","Colour: Natural matte","Corresponding gig bag: Article Nr 216015 (not included)"],[]),
    new Product(45652,"Harley Benton Ukulele UK-11DW Brown",3,2,70,["Ukulele","With laminated top","Back and sides: Basswood","Fretboard: Roseacer","12 Frets","Scale: 348 mm","Nut width: 35 mm","Open retro-style machine heads","Total length of the ukulele: 52 cm","Colour: Light brown","Gig bag included"],[]),
    new Product(20052536,"Kai KCI-700 Concert Ukulele",3,2,90,["Ukulele","Concert size","Top: Solid cedar","Back and sides: Bocote","Neck: Nato","Fretboard and bridge: Macassar","18 Frets","Nut and saddle: Nubone","Chrome-plated guitar machine heads","Scale: 37.5 cm","Nut width: 3.5 cm","Colour: Natural high gloss","Gig bag included"],[]),
    new Product(6312,"Harley Benton Kahuna CLU-32C",3,2,120,["Ukulele","Custom Line Kahuna Series","Concert size","Body: Spalted maple","Arched back","Neck: Sapele","Neck profile: C","Fretboard: Blackwood (Pinus Radiata)","Dot fretboard inlays","18 Frets","Scale: 377 mm","Nut width: 35 mm","Bridge: Blackwood (Pinus Radiata)","Black open-geared machine heads","Aquila strings","Total length: 62 cm","Width of the lower part: 20 cm","Colour: High gloss natural","Matching case: Article Nr: 223359 (not included)"],[]),
    new Product(49652,"Harley Benton Ukulele Pack Soprano",3,2,67,["Ukulele Set","Harley Benton UK11-DW soprano ukulele","Laminated top","Basswood back and sides","Roseacer fretboard (thermally treated maple wood)","Entire length of the ukulele: 52 cm","Scale: 35 cm","Colour: Natural matte","Includes a gig bag, simple instructions for how to play the first chords, chromatic clip-tuner, strings and picks"],[]),
    new Product(102896,"Kai KTI-700 Tenor Ukulele",3,2,95,["Ukulele","Tenor size","Top: Solid Cedar","Back & sides: Bocote","Neck: Nato","Fretboard & bridge: Morado","18 Frets","Nut & saddles: Nubone","Chrome-plated guitar machine heads","Scale: 43 cm","Nut width: 34 mm","Colour: Natural high gloss","Incl. KTB 100 gig bag"],[]),
    new Product(775462,"Harley Benton UK-12C Black",3,2,150,["Concert Ukulele","Body: Basswood","Neck: Maple","Fretboard: Maple","18 Frets","Scale: 384 mm","Nut width: 35 mm","Retro-style machine heads","Colour: Black","Includes a gig bag"],[],true),
    new Product(668159,"Kala Baritone Ukulele with Cutaway",3,2,160,["Ukulele","Baritone body size","With cutaway","Top: Solid spruce","Bottom and sides: Striped ebony","Neck: Mahogany","GraphTech NuBone saddle and nut","Fretboard & bridge: Striped ebony","19 Nickel silver frets","Scale: 514 mm","Mahogany binding","Fishman Kula electronics","Open geared machine heads with black tuning knobs","Chrome hardware","Original stringing: Aquila Super Nylgut","Total length: 775 mm","Finish: Matte","Includes baritone bag (UB-B)","Note: Register your product at www"],[]),
    new Product(495515,"Harley Benton UK-11C Brown",3,2,165,["Concert Ukulele","Basswood body","Maple neck","Roseacer (thermally treated maple wood) fretboard","18 Frets","Scale: 384 mm","Nut width: 35 mm","Open retro-style machine heads","Overall length: Approx. 610 mm","Colour: Brown","Includes a gig bag"],[]),
    new Product(943378,"Harley Benton UK-12 Magenta Pink",3,2,420,["Soprano Ukulele","Body: Basswood","Neck: Basswood","Fretboard: Roseacer","12 Nickel silver frets","Individual machine heads","Total length: 53 cm","Neck width: 35 mm","Scale: 348 mm","Retro-style machine heads","Colour: Magenta Pink","Gig bag included"],[]),
    new Product(6489,"Millenium MPS-750X E-Drum Mesh Se",4,0,450,["Complete Electric Drum Set","Drum module with 20 presets and 20 user kits","697 Sounds","55 Songs","4-Band equaliser","Fader for controlling the volume of the pads, the effects or the equaliser","Line Out (L/R)","Headphone output","Line in","USB","2 Additional trigger inputs","Bluetooth","Power adapter, cabling and sticks included"],[]),
    new Product(1269,"Millenium MPS-150X E-Drum Mesh Set",4,0,360,["108 Sounds","10 Drum kits","40 Songs","Metronome tempo 30-280","Integrated reverb","2x 6.3mm Mono jack outputs","3.5 mm Stereo line-in jack","3.5 mm Stereo headphone output","MIDI out","USB for MIDI connection","Set configuration:"],[]),
    new Product(4786,"Millenium MPS-850 E-Drum Set",4,0,470,["550 Voices","30 Preset kits","20 User kits","100 Songs","2 User Songs","Quick Record","Metronome","Equaliser for each kit","Pitch","Reverb","Compressor","6 Faders to adjust the volume of individual pads, metronome and songs","2x 6.3 mm jack main outputs","1x 6.3 mm stereo jack headphone output","1x 3.5 mm stereo jack line input","2x 6.3 mm stereo jack trigger inputs (already occupied by second crash and fourth tom pad)","USB-MIDI","USB memory","MIDI in/out","Set configuration:"],[]),
    new Product(4123,"Alesis Strike Pro Special Edition",4,0,750,["Strike Performance Drum Module","1800 Sounds","136 Kits","4.3","Colour LED display","Sample your own sounds (wav. files) with the included 16 GB SD card","Module configuration with Strike Software Editor","12-Channel mixer","Effects section with reverb, flanger, chorus, vibrato and delay","Sample record","12x 6.3 mm Stereo jack trigger inputs","2x 6.3 mm Jack main outputs (balanced)","6x 6.3 mm Jack direct outputs (balanced)","1x 6.3 mm Stereo jack headphone output","1x 3.5 mm Stereo jack line input","SD Card slot (max. 64 GB)","USB MIDI","MIDI Input/Output","Drum shells are made from hybrid wood","Latest-generation mesh heads for most natural response ever","Black and gold rack mounting hardware","Cymbals feature the hammer marks","Includes drum rack, snare stand, power supply, cables and sticks","Set Configuration:"],[],true),
    new Product(3495,"Alesis Debut Kit",4,0,643,["Complete e-drum set for beginners","Thanks to its compact dimensions and small spaces, it is also ideal for children and very space-saving","10 Drum kits","120 Sounds","30 Patterns","Metronome 30-280 bpm","Line output: 2x 6.3 mm jack","Headphone output: 3.5 mm stereo jack","Aux-in: 3.5 mm stereo jack","USB-MIDI","Includes seat, sticks, headphones and wiring"],[]),
    new Product(3945,"Alesis Strike Pro Special Edit Bundle",4,0,640,["V-Drums","728 Sounds","55 Preset Kits","45 User kits","Prismatic Sound Modeling technology","Bluetooth 4.2 transceiver for the direct and wireless streaming of music from your smartphone or MIDI to compatible devices","Sample reverb (IR) puts very realistic room reverbs at your fingertips","Up to 500 WAV samples can be imported (max. length of 24 minutes mono)","Quick record","SD card slot (SDHC compatible)","Multi-pin connector (trigger input) for 8 pads","4x 6.3 mm Jack trigger inputs for additional pads","3x Digital trigger inputs for Roland digital drum pads with multi-sensor technology","2x 6.3 mm Jack main outputs","2x 6.3 mm Jack direct outputs","6.3 mm Jack headphone output","3.5 mm Stereo jack mix input","6.3 mm Jack footswitch input","MIDI Input/Output","USB Type B connector for USB audio and USB MIDI","Includes cables and power supply unit","Set configuration:"],[]),
    new Product(3165,"Alesis Turbo Mesh Kit",4,0,560,["Tom and snare pad equipped with Mesh heads","Turbo drum module with 120 sounds","10 Drum kits","30 Integrated Play-Along tracks","Training and metronome features","CD/MP3 AUX input for play-along songs","USB/MIDI port for playing with virtual instruments and recording","Stereo line outputs and headphone output"],[]),
    new Product(9469,"Roland TD-27KV V-Drum Set",4,0,640,["V-Drums","728 Sounds","55 Preset Kits","45 User kits","Prismatic Sound Modeling technology","Bluetooth 4.2 transceiver for the direct and wireless streaming of music from your smartphone or MIDI to compatible devices","Sample reverb (IR) puts very realistic room reverbs at your fingertips","Up to 500 WAV samples can be imported (max. length of 24 minutes mono)","Quick record","SD card slot (SDHC compatible)","Multi-pin connector (trigger input) for 8 pads","4x 6.3 mm Jack trigger inputs for additional pads","3x Digital trigger inputs for Roland digital drum pads with multi-sensor technology","2x 6.3 mm Jack main outputs","2x 6.3 mm Jack direct outputs","6.3 mm Jack headphone output","3.5 mm Stereo jack mix input","6.3 mm Jack footswitch input","MIDI Input/Output","USB Type B connector for USB audio and USB MIDI","Includes cables and power supply unit","Set configuration:"],[]),
    new Product(5548,"Millenium Youngster Drum Set Green",4,1,680,["Perfect for drummers as of 3 years old","Shell material: Hardwood","Black hardware","Drum shell with robust film finish","Colour: Green Sparkle"],[]),
    new Product(7985,"Millenium Youngster Drum Set Azure",4,1,950,["Perfect for drummers as of 3 years old","Shell material: Hardwood","Black hardware","Drum shell with robust film finish","Colour: Azure Sparkle","Consists of:","16 x 12"," Bass drum","08 x 05 Tom Tom","10 x 04","Snare Drum","Snare stand","Hi-hat stand","Pedal","Stool","1 Pair of drumsticks","Including LowNoiz cymbals, which are characterised by lower volume and a fast finish"],[]),
    new Product(13265,"Startone Star Drum Set Studio -BK",4,1,650,["5-Piece drum set, ideal for beginners","6-Ply tom- and snare drum shells made from poplar wood","9-Ply bass drum made from poplar wood","Drum shells feature a wrap finish","The ultimate entry level drum set with an added fun factor!","Colour: Black","Includes a drum throne"],[]),
    new Product(12302,"Millenium Youngster Drum Set Silver",4,1,600,["Perfect for drummers as of 3 years old","Shell material: Hardwood","Black hardware","Drum shell with robust film finish","Colour: Silver","16 x 12"," Bass drum","08 x 05"," Tom Tom","10  04"," Snare Drum","Snare stand","Hi-hat stand","Pedal","Stool","1 Pair of drumsticks","Including LowNoiz cymbals, which are characterised by lower volume and a fast finish"],[]),
    new Product(20202,"Pearl Decade Maple Standard S. Black",4,1,750,["Drum Set","Decade Maple Series","Standard version","DMP925S/C-227","Matte lacquered shells","Chrome shell hardware","Shells made of thin 6-ply maple with 5.4 mm wall thickness","1.6 mm triple-flanged hoops","OptiLoc tom mounting system","Remo Ambassador UT and Remo Powerstroke 3 (bass drum) heads","Bass drum resonant head with sound hole","Highly responsive set with great tonal and dynamic range","Colour: Satin Black Slate (-227)","Bass drum damping cushion included"],[]),
    new Product(9090,"Ludwig Classic Maple 4pcs G. Blue",4,1,640,["Shell Set","Classic Maple Series","Exclusively available at Thomann","7-Ply maple shells","Large Classic Lugs","A.T.L.A.S. mount on the tom","Triad stand tom brackets and legs","Elite Bass Drum Legs","Colour: Glacier Blue","Includes PM0048 single tom holder","Made in USA"],[]),
    new Product(3120,"Pearl Reference Pure Studio Set #201",4,1,760,["Drum Shell Kit","Reference Pure Series","RFP904XEP-201","Colour: matte walnut (#201)","Chrome hardware","Lugs: STL (swivel tube lugs) featuring a unique swivel function","FatTone 1,6 mm metal hoops","Aluminium Optimount tom tom holder","Reference drum shells impress via a combination of task specific bearing edges and wood combinations","Bass drum is with 4 inner plies from mahogany and 2 outer plies from maple","10 Tom with 4 outer plies from maple and 2 inner plies from birch"," Tom with 6 plies of maple","14","Floor tom with mahogany on the inside for deep, full frequencies and the accentuated warmth of the surrounduíng maple wood"],[]),
    new Product(78459,"DW Finish Ply Set Broken Glass",4,1,549,["Drum Shell Set","Collector's Finish Ply Series","Maple shell in SSC+ construction","Chrome hardware","STM tom holder","Foil covered shells","Truehoop tension hoops","True Pitch 50 tension screws","Set assembled using the Timbre Matched","process - all shells are analyzed according to their specific fundamental tone and then combined to create a set that is tonally matched","Colour: Broken Glass"],[]),
    new Product(10232,"Sonor SQ2 Set Studio Scand. Birch II",4,1,560,["Sonor SQ2 Shell Set Maple Studio Scandinavian Birch II","100% Maple Shell","Colour: Scandinavian Birch (veneer, high gloss finish)","Shell Set consisting of: 20","x16 Bass drum (medium) with matching hoops, 10","x 08","tom tom, 12 ","x 08 tom tom (vintage), 14" ," 13 floor tom (vintage), chrome hardware, thumbscrews for bass drum, square screws for toms and stand tom","Medium white roughened batter heads and medium clear resonance heads for toms","Batter head (bass drum): Power, transparent","Resonance head: Powerstroke 3 natural with Sonor logo and Sonor SQ2 logo",],[]),
    new Product(8,"Millenium HD-120 E-Drum Set",4,0,275,["Complete e-drum set for beginners","Due to the compact dimensions and short distances also ideal for children","Very space-saving - required footprint: 100 x 60 cm","12 Drum kits","Metronome 40-240 bpm","3.5 mm Mono jack line output","3.5 mm Stereo jack headphone output","3.5 mm Stereo jack Aux-In","USB MIDI","Includes cabling, seat, headphones, sticks, stick holder and power supply (100-240V)"],[],true),
    new Product(9,"Alesis Crimson II SE Mesh Kit",4,0,["Crimson II drum module with 671 sounds","54 Preset and 20 user kits"," dynamically changes sound nuances while playing","Real-time recording","6.3 mm mono jack outputs (L/R) for connecting to speakers or mixers","2x 6.3 mm mono jack aux outputs","3.5 Mm, stereo jack headphone output","3.5 mm stereo jack input for connecting an MP3 or CD player","MIDI input and output","USB for MIDI connections and for loading new songs from a USB stick","Drum rack and snare stand included","Set configuration:"],[]),
    new Product(36392969,"Thomann Student Violinset 4/4",3,0,120,["Violin Set","Size: 4/4","Top: Solid spruce","Bottom, sides and neck: Maple","Ebony fingerboard","Pegs made of jujube","4 Fine tuners","Includes fibreglass bow, case and rosin","Made ready to play in Germany in the Thomann specialist string workshop"],[]),
    new Product(2649546,"Harley Benton HBV 800NV E-Violin 4/4",3,0,75,["Electric-Acoustic Violin","Top: Spruce","Back & Neck: Maple","Fingerboard: Ebony (Diospyros ebenum)","Tuning pegs: Jujube (Ziziphus jujuba)","Pickup system: Passive piezoceramic","Tone and volume control for amplified and non-amplified playing","Colour: Natural lacquer finish","Includes a case, composite bow, rosin and a cable","Set up in Germany at Thomann's strings workshop"],[]),
    new Product(6494347,"Harley Benton HBV 800BK E-Violin 4/4",3,0,89,["Electric-Acoustic Violin","Top: Spruce","Back & Neck: Maple","Fingerboard: Ebony (Diospyros ebenum)","Tuning pegs: Jujube (Ziziphus jujuba)","Pickup system: Passive piezoceramic","Tone and volume control for amplified and non-amplified playing","Includes a case, composite bow, rosin and a cable","Colour: Black","Set up in Germany at Thomann's strings workshop"],[]),
    new Product(4885569,"Harley Benton HBV 990BCF 4/4 Electric Violin",3,0,67,["Electric Violin","Size: 4/4","Maple body","Maple neck","Plastic frame","Birch fingerboard","Jujube tuning pegs and chinrest","Active pickup system","Headphone output","Jack output","Design: Black Carbon Fiber","Includes a case, shoulder rest, composite bow, rosin and 9V battery"],[]),
    new Product(9857671,"Roth & Junius RJV-S Student Violin Set 4/4",3,0,95,["Violin Set","Size: 4/4","Made of European spruce and European maple","Solid spruce top","Solid maple bottom","Maple neck and sides","Ebony fingerboard","Ebony pegs","Fine tuning tailpiece","With Thomastik Dominant stringing","Includes case, rosin and bow"],[]),
    new Product(649239,"Harley Benton HBV 990BK Electric Violin",3,0,200,["Electric Violin","Size: 4/4","Active pickup system","Headphone output","Jack output","Body: Basswood","Frame: Plastic","Fingerboard and tuning pegs: Birch","Colour: Black","Includes a case, shoulder rest, composite bow, rosin and 9V battery"],[]),
    new Product(4189856,"Stentor SR1500 Violin Student II 4/4",3,0,315,["Student Violin Outfit","Size: 4/4","Solid spruce top","Solid maple body","Ebony pegs and fingerboard","Hardwood chinrest","Includes case and bow"],[]),
    new Product(9561476,"Harley Benton HBV 990WH Electric Violin",3,0,160,["Electric Violin","Size: 4/4","Active pickup system","Headphone output","Jack output","Body: Basswood","Frame: Plastic","Fingerboard and tuning pegs: Birch","Colour: White","Includes a case, shoulder rest, composite bow, rosin and a 9V battery"],[]),
    new Product(6485840,"Alfred Stingl by Höfner AS160 EV Electric Violin",3,0,450["Electrical Violin","Solid spruce top","Maple ribs","Maple back","Ebony pegs","Ebony finger board","Active Piezo-Pickup system","Sound controls (High/Low/Volume)","Tailpiece with fine tuners","Including case and headphones"],[]),
    new Product(2,"Harley Benton Custom Line CLD-41SE WN",0,1, 289, ["Dreadnought design","Dovetail construction","Solid sitka spruce top","Scalloped X-bracing","Walnut body","Mahogany neck","Pau Ferro fretboard","Abalone Hexagon fretboard inlays","Abalone body binding","White fretboard and headstock binding","Modified Oval C neck profile","Scale: 643 mm","Nut width: 43 mm","Bone nut","20 Frets","Compensated saddle","Pau Ferro bridge","Gold-plated diecast DLX machine heads","Pickup system: Fishman Presys-II preamp system with built-in tuner","Strings: D'Addario XTAPB1253 Light (Article Nr 471307), .012 - .053","Colour: Natural matte"],[harleyBentonCLDImage,harleyBentonCLD_1Image ]),
    new Product(3455663,"Takamine EF341SC", 0,1,839,["Bruce Springsteen model","Body shape: Dreadnought with cutaway","Body and sides: Maple","Top: Solid cedar","Bridge and fingerboard: Rosewood (Dalbergia Latifolia)","Fretboard inlays: Mother of pearl snowflake dots","CT4B preamp with pickup and tuner","Ex-factory stringing: Daddario EXP16 .012 - .053 (Article Nr 147540)","Colour: High gloss black","Case included"],[TakamineEF341SCImage, TakamineEF341SC_1Image, TakamineEF341SC_2Image, TakamineEF341SC_3Image]),
    new Product(76677764,"Fender CD-60 SB V3",0,1,105,["Design: Dreadnought","Top: Laminated spruce","Bottom and sides: Laminated mahogany","Neck: Mahogany","Fretboard and bridge: Walnut","20 Frets","Scale: 643 mm","Nut width: 43 mm (1.69)","Colour: Sunburst","Strings: Fender 880L (Art.254209)"],[FenderCDSBV3Image, FenderCDSBV3_1Image, FenderCDSBV3_2Image]),
    new Product(106663456,"Epiphone J-15 EC Deluxe NA,",0,1,165,["Spruce top","Mahogany body","Set-in neck attachment","Okoume neck","Pau Ferro fretboard","Dots fretboard inlays","Slim taper D profile neck profile","Scale: 647 mm","Nut width: 42.6 mm","20 Medium frets","Fishman pickup system","D'Addario strings, .012 - .053","Colour: Natural","Includes a case"],[]),
    new Product(111110116,"Gibson G-45 Natural Generation",0,1,918,["Generation Collection","J-45 shape","Top: Solid Sitka spruce","Back and sides: Solid walnut","Neck: Utile","Fingerboard: Striped ebony","Neck profile: Advanced Response","Dovetail neck joint","Player Port in the upper bout","Scale: 628 mm (24.75)","20 frets","Rectangular ebony bridge","Grover Mini Rotomatic machine heads","Finish: Nitrocellulose","Colour: Natural","Includes soft case","Made in Bozeman, USA"],[]),
    new Product(12388956,"Harley Benton Custom Line CLD-15M",0,1,139,["Steel-String Guitar","Design: Dreadnought with dovetail construction","Top: Solid mahogany","Scalloped X-bracing","Body: Mahogany","Neck: Mahogany","Fretboard: Pau Ferro","Neck profile: Modified Oval C","Fretboard inlays: Mother-of-pearl Snowflake","Body binding: Wooden","Scale: 643 mm","Nut width: 43 mm","20 Frets","Nut: Bone","Saddle: Compensated bone","Bridge: Pau Ferro","Machine heads: Chrome-plated diecast DLX","Strings: D'Addario XTAPB1253 Light, .012 - .053 (Article Nr 471307)","Colour: Natural matte"],[]),
    new Product(130747,"Epiphone Hummingbird Studio FCB",0,1,230,["Steel-String Guitar with Pickup","Solid spruce top","Mahogany back and sides","Mahogany neck","Pau Ferro fretboard","Scale: 629 mm","Nut width: 42.8 mm","Slim Taper D neck profile","20 Frets","Pearloid parallelogram fretboard inlays","Fishman Sonitone pickup system","Pickguard is decorated with original hummingbird artwork","Pau Ferro bridge","Grover machine heads","Total length: 106 cm","Colour: Faded Cherry Burst"],[]),
    new Product(2033473,"Ramirez Estudio 3 Cedar",0,1,1280,["Classical Guitar","Made from selected woods","Solid cedar top","Solid Indian rosewood back and sides","Cedro neck","Ebony fretboard","Nut width: 52 mm","Scale: 650 mm","Gold-plated machine heads","High Tension 3rd Carbon strings","Colour: Natural high-gloss","Includes a Tonträger case"],[]),
    new Product(217656532,"Ramirez Estudio 3 Spruce",0,1,1180["Classical Guitar","Selected woods","Solid spruce top","Back and sides made of solid Indian rosewood (Dalbergia latifolia)","Cedar neck","Ebony fretboard","Scale: 650 mm","Nut width: 52 mm","Gold-plated machine heads","Stringing from Fac: Ramírez High-tension, 3rd carbon","Colour: Natural, high-gloss","Includes sound carrier case"],[]),
    new Product(23244261,"La Mancha Romero Granito 32-CE-N",0,1,177,["Classical Guitar","Size: 4/4","Design: Narrow neck with cutaway","Top: Spruce","Bottom and sides: Mahogany","Neck: Mahogany","Fretboard and bridge: Ovangkol","Nickel-plated machine heads with black buttons","Black ABS binding","Savarez strings","Scale: 650 mm","Nut width: 48 mm","BR-1 pickup system","Finish: Open pore","Colour: Natural matte"],[]),
    new Product(2376761,"La Mancha Granito 32-N-SCC",0,1,120,["Classical Guitar","Size: 4/4","Neck profile: Narrow","Top: Spruce","Back and sides: Mahogany","Neck: Mahogany","Fretboard and bridge: Ovangkol","Nut and saddle: NuBone","Machine heads: Nickel-plated with black buttons","Bindings: rw ABS","Strings: Savarez","Scale: 650 mm","Nut width: 48 mm","Finish: Screwed Charcoal Matte Open-Pore"],[]),
    new Product(2599896740,"Cordoba C5",0,1,140,["Classical Guitar","Top: Solid cedar","Back & Sides: Mahogany veneer","Fretboard: Rosewood (Dalbergia latifolia)","Scale: 650 mm","Nut width: 52 mm","Machine heads: Gold-plated","Colour: Natural"],[]),
    new Product(2522233490,"Alhambra Z Nature CW EZ incl.Gig Bag",0,1,135,["Classical Guitar with Pickup","With cutaway","Top: Solid cedar","Back and sides: Sapelli","Neck: Sapelli","Fretboard and bridge: Rosewood","Scale: 650 mm","Nut width: 50 mm (1.97)","Bone nut","Fishman Classic II pickup system","Finish: Open-pored","Colour: Natural","Gig bag included"],[]),
    new Product(26112009097,"Fender CN-60S Natural WN",0,1,176,["Classical guitar","Top: Solid spruce","Back & Sides: Mahogany, laminated","Neck: Mahogany","Fretboard: Walnut","18 Frets","Nut width: 43 mm","Scale: 643 mm","CD pearloid rosette","Strings: Fender 100 Classic (Article Nr: 241736)","Colour: Natural (high-gloss)"],[]),
    new Product(40444,"Sonor SQ2 Rock Set Maple Walnut Root",4,1,950,["Drum Shell Set","Drum shell: Maple","Shell surface inside: Natural","Shell type: Medium","Hardware: Chrome","Bass drum with thumbscrews","Tom/floor toms with square head bolts","Batter heads for tomtoms: Medium white roughened","Resonance heads for tomtoms: Medium, transparent","Head bass drum: Power, transparent","Resonance head bass drum: Powerstroke 3, white smooth with SONOR and SQ2 Logo","Colour: Walnut roots (high gloss finish)"],[]) 
];

export default Products;